// Auto-stable subset of generated/proto/_unified message_id mapping.
// Source of truth: proto/message_id.txt (regenerated by tools/proto-gen).
// Keep this file aligned with whichever IDs the client actually uses.
namespace MmorpgClient.Net
{
    public static class MessageIds
    {
        // ── login (Go service via Gate gRPC bridge) ──────────────
        public const uint Login         = 48; // ClientPlayerLogin.Login
        public const uint CreatePlayer  = 14; // ClientPlayerLogin.CreatePlayer
        public const uint EnterGame     = 26; // ClientPlayerLogin.EnterGame
        public const uint LeaveGame     = 17; // ClientPlayerLogin.LeaveGame
        // RefreshToken is not in the static message_id.txt snapshot embedded
        // in this client; the server allocates the ID dynamically via
        // build.bat. The runtime registry lives in the parent repo and a
        // future drop will surface it through a generated constants file --
        // for now the refresh ticker is gated behind a non-zero check.
        public const uint RefreshToken = 0;

        // ── scene C2S ────────────────────────────────────────────
        public const uint EnterScene    = 63; // SceneSceneClientPlayer.EnterScene
        public const uint SceneInfoC2S  = 43; // SceneSceneClientPlayer.SceneInfoC2S
        public const uint ReleaseSkill  = 84; // SceneSkillClientPlayer.ReleaseSkill
        public const uint ListSkills    = 77; // SceneSkillClientPlayer.ListSkills

        // ── scene S2C notifications ──────────────────────────────
        public const uint NotifyEnterScene       = 79;
        public const uint NotifySceneInfo        = 31;
        public const uint NotifyActorCreate      = 21;
        public const uint NotifyActorListCreate  = 47;
        public const uint NotifyActorDestroy     = 51;
        public const uint NotifyActorListDestroy = 64;
        public const uint NotifySkillUsed        = 70;
        public const uint NotifySkillInterrupted = 33;
        public const uint TipToClient            = 23; // SceneClientPlayerCommon.SendTipToClient
        public const uint KickPlayer             = 34;
    }
}
