// <auto-generated>
// Generated by tools/gen_messageids.ps1 from proto/message_id.txt.
// Do not edit by hand. Re-run after the server regenerates IDs.
// </auto-generated>
namespace MmorpgClient.Net
{
    public static class MessageIds
    {
        public const uint CreatePlayer           =   14; // ClientPlayerLoginCreatePlayer
        public const uint Disconnect             =   58; // ClientPlayerLoginDisconnect
        public const uint EnterGame              =   26; // ClientPlayerLoginEnterGame
        public const uint EnterScene             =   63; // SceneSceneClientPlayerEnterScene
        public const uint KickPlayer             =   34; // SceneClientPlayerCommonKickPlayer
        public const uint LeaveGame              =   17; // ClientPlayerLoginLeaveGame
        public const uint ListSkills             =   77; // SceneSkillClientPlayerListSkills
        public const uint Login                  =   48; // ClientPlayerLoginLogin
        public const uint NotifyActorCreate      =   21; // SceneSceneClientPlayerNotifyActorCreate
        public const uint NotifyActorDestroy     =   51; // SceneSceneClientPlayerNotifyActorDestroy
        public const uint NotifyActorListCreate  =   47; // SceneSceneClientPlayerNotifyActorListCreate
        public const uint NotifyActorListDestroy =   64; // SceneSceneClientPlayerNotifyActorListDestroy
        public const uint NotifyEnterScene       =   79; // SceneSceneClientPlayerNotifyEnterScene
        public const uint NotifySceneInfo        =   31; // SceneSceneClientPlayerNotifySceneInfo
        public const uint NotifySkillInterrupted =   33; // SceneSkillClientPlayerNotifySkillInterrupted
        public const uint NotifySkillUsed        =   70; // SceneSkillClientPlayerNotifySkillUsed
        public const uint RefreshToken           =  127; // ClientPlayerLoginRefreshToken
        public const uint ReleaseSkill           =   84; // SceneSkillClientPlayerReleaseSkill
        public const uint SceneInfoC2S           =   43; // SceneSceneClientPlayerSceneInfoC2S
        public const uint TipToClient            =   23; // SceneClientPlayerCommonSendTipToClient
    }
}
